// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmoufommkbpdpbwvfhbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtb3Vmb21ta2JwZHBid3ZmaGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTcwMDgsImV4cCI6MjA3Mjk5MzAwOH0.hRUheOApUIkMM3Hey47-u5M6hqrb8d_AhHaRZcvxHXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});